### ISSUE TITLE
204 No content

### ISSUE THREAD

**Issue by Diokuz** [pasaran/descript#122]
При попытке выполнения блока

```js
de.http('{state.urlDirectory}/groups/{.groupId}/', {
    timeout: '5000',
    method: 'DELETE',
    headers: {
        'Content-Type': 'application/json'
    },
    result: function(data) {
        return data;
    }
})
```

Запрос проходит, но в консоль падает ошибка

```
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at de.Result.Raw.object (/home/diokuz/dir/node_modules/descript/lib/de.result.js:209:75)
    at Array.<anonymous> (/home/diokuz/dir/node_modules/descript/lib/de.block.js:345:66)
    at no.Promise.resolve (/home/diokuz/dir/node_modules/descript/node_modules/nommon/lib/no.promise.js:146:21)
    at Array.<anonymous> (/home/diokuz/dir/node_modules/descript/lib/de.block.js:632:25)
    at no.Promise.resolve (/home/diokuz/dir/node_modules/descript/node_modules/nommon/lib/no.promise.js:146:21)
    at IncomingMessage.<anonymous> (/home/diokuz/dir/node_modules/descript/lib/de.http.js:164:29)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:891:12)
```

По-видимому, проблема в том, что descript не обрабатывает ответы сервера, в которых нет body. К таковым относятся 204, и некоторые другие.

Хотелось бы оперативно поддержать, т.к. сейчас это блокирует один из релизов.
Хотя бы чтоб не падало.

**Comment by pasaran** [comment]
Хмм.

Нашел в коде опцию `only_status` у http-блока:
```
de.http( '...', {
    only_status: true,
    ...
} )
```

Оно немного для другого было сделано, если я правильно помню, но, возможно, что и сработает так. Костыль, конечно, но если срочно, то попробуй так.

**Comment by pasaran** [comment]
Еще вариант, выставить правильный `data_type`. По-дефолту он `json` и при попытки распарсить пустую строку как json все падает.
Можно поставить `data_type: 'text'`.
